version: '3'

networks:
  deploy-guide-dev:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Mail
    networks:
      - deploy-guide-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  smtp:
    container_name: smtp
    build:
      context: ./internal/smtp_server
      dockerfile: Dockerfile
    ports:
      - "25:587"
    networks:
      - deploy-guide-dev

  auth:
    container_name: auth
    build:
      context: ./internal/auth
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "8004:8004"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  email:
    container_name: email
    build:
      context: ./internal/email
      dockerfile: ./cmd/email/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  session:
    container_name: session
    build:
      context: ./internal/session
      dockerfile: ./cmd/session/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  user:
    container_name: user
    build:
      context: ./internal/user
      dockerfile: ./cmd/user/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

volumes:
  postgres_data: