version: '3'

networks:
  deploy-guide-dev:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Mail
    networks:
      - deploy-guide-dev
    volumes:
      - db_postgres_data:/var/lib/postgresql/data

  db_question:
    container_name: db_question
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Question
    networks:
      - deploy-guide-dev
    volumes:
      - db_question_postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  smtp:
    container_name: smtp
    build:
      context: ./internal/smtp_server
      dockerfile: Dockerfile
    ports:
      - "25:587"
    networks:
      - deploy-guide-dev

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "8004:8004"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  email:
    container_name: email
    build:
      context: .
      dockerfile: ./cmd/email/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  session:
    container_name: session
    build:
      context: .
      dockerfile: ./cmd/session/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  user:
    container_name: user
    build:
      context: .
      dockerfile: ./cmd/user/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  folder:
    container_name: folder
    build:
      context: .
      dockerfile: ./cmd/folder/Dockerfile
    ports:
      - "8005:8005"
    networks:
      - deploy-guide-dev
    depends_on:
      - db

  questionnaire:
    container_name: questionnaire
    build:
      context: .
      dockerfile: ./cmd/questionnaire/Dockerfile
    ports:
      - "8006:8006"
    networks:
      - deploy-guide-dev
    depends_on:
      - db_question

volumes:
  db_postgres_data:
  db_question_postgres_data: