basePath: /
definitions:
  delivery.Email:
    type: object
  delivery.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  delivery.Response:
    properties:
      body: {}
      status:
        type: integer
    type: object
  delivery.UserSwag:
    properties:
      avatar:
        description: AvatarID stores the identifier of the user's avatar image.
        type: string
      birthday:
        description: Birthday stores the birthdate of the user.
        type: string
      description:
        description: Description stores additional information about the user.
        type: string
      firstname:
        description: FirstName stores the first name of the user.
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/models.UserGender'
        description: Gender stores the gender of the user.
      id:
        description: ID uniquely identifies the user.
        type: integer
      login:
        description: Login is the username used for authentication.
        type: string
      middle-name:
        description: Patronymic stores the middle name of the user, if available.
        type: string
      password:
        description: Password is the hashed password of the user.
        type: string
      phone-number:
        description: PhoneNumber stores the phone number of the user.
        type: string
      surname:
        description: Surname stores the last name of the user.
        type: string
    type: object
  models.UserGender:
    enum:
    - Male
    - Female
    - Other
    type: string
    x-enum-varnames:
    - Male
    - Female
    - Other
host: localhost:8080
info:
  contact: {}
  description: API server for mail
  title: API Mail
  version: "1.0"
paths:
  /api/v1/auth/get-user:
    get:
      description: Retrieve the user associated with the current session
      produces:
      - application/json
      responses:
        "200":
          description: User details
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Not Authorized
          schema:
            $ref: '#/definitions/delivery.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: Get user by session
      tags:
      - users
  /api/v1/auth/verify-auth:
    get:
      description: Verify user authentication using sessions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Not Authorized
          schema:
            $ref: '#/definitions/delivery.Response'
      summary: Verify user authentication
      tags:
      - users
  /api/v1/email/{id}:
    get:
      description: Get an email message by its unique identifier
      parameters:
      - description: ID of the email message
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Email message data
          schema:
            $ref: '#/definitions/delivery.Response'
        "400":
          description: Bad id in request
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Not Authorized
          schema:
            $ref: '#/definitions/delivery.Response'
        "404":
          description: Email not found
          schema:
            $ref: '#/definitions/delivery.Response'
      summary: Get an email message by ID
  /api/v1/email/add:
    post:
      consumes:
      - application/json
      description: Add a new email message to the system
      parameters:
      - description: Email message in JSON format
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/delivery.Email'
      produces:
      - application/json
      responses:
        "200":
          description: ID of the added email message
          schema:
            $ref: '#/definitions/delivery.Response'
        "400":
          description: Bad JSON in request
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Not Authorized
          schema:
            $ref: '#/definitions/delivery.Response'
        "500":
          description: Failed to add email message
          schema:
            $ref: '#/definitions/delivery.Response'
      summary: Add a new email message
  /api/v1/email/delete/{id}:
    delete:
      description: Delete an email message based on its identifier
      parameters:
      - description: ID of the email message
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Deletion success status
          schema:
            $ref: '#/definitions/delivery.Response'
        "400":
          description: Bad id
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Not Authorized
          schema:
            $ref: '#/definitions/delivery.Response'
        "500":
          description: Failed to delete email message
          schema:
            $ref: '#/definitions/delivery.Response'
      summary: Delete an email message
  /api/v1/email/update/{id}:
    put:
      consumes:
      - application/json
      description: Update an existing email message based on its identifier
      parameters:
      - description: ID of the email message
        in: path
        name: id
        required: true
        type: integer
      - description: Email message in JSON format
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/delivery.Email'
      produces:
      - application/json
      responses:
        "200":
          description: Update success status
          schema:
            $ref: '#/definitions/delivery.Response'
        "400":
          description: Bad id or Bad JSON
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Not Authorized
          schema:
            $ref: '#/definitions/delivery.Response'
        "500":
          description: Failed to update email message
          schema:
            $ref: '#/definitions/delivery.Response'
      summary: Update an email message
  /api/v1/emails:
    get:
      description: Get a list of all email messages
      produces:
      - application/json
      responses:
        "200":
          description: List of all email messages
          schema:
            $ref: '#/definitions/delivery.Response'
        "401":
          description: Not Authorized
          schema:
            $ref: '#/definitions/delivery.Response'
        "404":
          description: DB error
          schema:
            $ref: '#/definitions/delivery.Response'
        "500":
          description: JSON encoding error
          schema:
            $ref: '#/definitions/delivery.Response'
      summary: Display the list of email messages
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Handles user login.
      parameters:
      - description: User credentials for login
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/delivery.UserSwag'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/delivery.Response'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "500":
          description: Failed to create session
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: User login
      tags:
      - users
  /api/v1/logout:
    post:
      description: Handles user logout.
      produces:
      - application/json
      responses:
        "200":
          description: Logout successful
          schema:
            $ref: '#/definitions/delivery.Response'
      summary: User logout
      tags:
      - users
  /api/v1/signup:
    post:
      consumes:
      - application/json
      description: Handles user signup.
      parameters:
      - description: New user details for signup
        in: body
        name: newUser
        required: true
        schema:
          $ref: '#/definitions/delivery.UserSwag'
      produces:
      - application/json
      responses:
        "200":
          description: Signup successful
          schema:
            $ref: '#/definitions/delivery.Response'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
        "500":
          description: Failed to add user
          schema:
            $ref: '#/definitions/delivery.ErrorResponse'
      summary: User signup
      tags:
      - users
swagger: "2.0"
