basePath: /
definitions:
  email.Email:
    properties:
      dateOfDispatch:
        description: Date when the email was sent.
        type: string
      deleted:
        description: Status indicating whether the email has been deleted.
        type: boolean
      draftStatus:
        description: Status indicating that the email is a draft.
        type: boolean
      id:
        description: Unique identifier of the email in the database.
        type: integer
      mark:
        description: A flag, for example, marking the email as a favorite.
        type: string
      photoId:
        description: Link to the photo attached to the email, if any.
        type: string
      readStatus:
        description: Status indicating whether the email has been read.
        type: boolean
      replyToEmailId:
        description: ID of the email to which a reply can be sent.
        type: integer
      text:
        description: Text body of the email.
        type: string
      topic:
        description: Subject of the email.
        type: string
    type: object
  user.User:
    properties:
      id:
        description: Unique identifier of the user.
        type: integer
      login:
        description: User's login.
        type: string
      name:
        description: User's first name.
        type: string
      password:
        description: User's password.
        type: string
      surname:
        description: User's last name.
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API server for mail
  title: API Mail
  version: "1.0"
paths:
  /email/{id}:
    get:
      description: Get an email message by its unique identifier
      parameters:
      - description: ID of the email message
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Get an email message by ID
  /email/add:
    post:
      consumes:
      - application/json
      description: Add a new email message to the system
      parameters:
      - description: Email message in JSON format
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/email.Email'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Add a new email message
  /email/delete/{id}:
    delete:
      description: Delete an email message based on its identifier
      parameters:
      - description: ID of the email message
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: Delete an email message
  /email/update/{id}:
    put:
      consumes:
      - application/json
      description: Update an existing email message based on its identifier
      parameters:
      - description: ID of the email message
        in: path
        name: id
        required: true
        type: integer
      - description: Email message in JSON format
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/email.Email'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: Update an email message
  /emails:
    get:
      description: Get a list of all email messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties:
                type: integer
              type: object
            type: array
      summary: Display the list of email messages
  /login:
    post:
      consumes:
      - application/json
      description: Handles user login.
      parameters:
      - description: User credentials for login
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/user.User'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
        "401":
          description: Invalid credentials
          schema:
            type: string
        "500":
          description: Failed to create session
          schema:
            type: string
      summary: User login
      tags:
      - users
  /logout:
    post:
      description: Handles user logout.
      produces:
      - application/json
      responses:
        "200":
          description: Logout successful
          schema:
            type: string
      summary: User logout
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      description: Handles user signup.
      parameters:
      - description: New user details for signup
        in: body
        name: newUser
        required: true
        schema:
          $ref: '#/definitions/user.User'
      produces:
      - application/json
      responses:
        "200":
          description: Signup successful
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to add user
          schema:
            type: string
      summary: User signup
      tags:
      - users
swagger: "2.0"
