name: CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed

jobs:

  deploy:
    name: Backend deploy
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
       - name: Pull docker image
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd backend_4/2024_1_Refugio/
             git pull