name: CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed

jobs:

  deploy:
    name: Backend deploy
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
       - name: git pull
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: | 
             cd backend_4/2024_1_Refugio/
             sudo git pull
       - name: Docker container stop
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd backend_4/2024_1_Refugio/
             sudo docker stop $(sudo docker ps -a -q)
             sudo docker rm $(sudo docker ps -a -q)
       - name: Docker compose build
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd backend_4/2024_1_Refugio/
             if [ -z "$(sudo docker ps -q)" ]; then
                echo "No running containers found."
             else
                sudo docker stop $(sudo docker ps -a -q)
                sudo docker rm $(sudo docker ps -a -q)
             fi
       - name: Pull docker images
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd backend_4/2024_1_Refugio/
             sudo docker-compose -f docker-compose-cd.yml pull
       - name: Run docker-compose
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd backend_4/2024_1_Refugio/
             sudo docker-compose -f docker-compose-cd.yml up --build -d
       - name: Clear old images and containers
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd backend_4/2024_1_Refugio/
             sudo docker container prune -f
             sudo docker images prune